---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - routes.yaml

namespace: konflux-kite

images:
  - name: quay.io/konflux-ci/kite-prod
    newTag: ef9cf97e2949abd49b725958250b40c59b63b8c9

  - name: quay.io/konflux-ci/kite-init
    newTag: ef9cf97e2949abd49b725958250b40c59b63b8c9

configMapGenerator:
  - name: kite-config
    namespace: konflux-kite
    literals:
      - KITE_PROJECT_ENV=production
      - KITE_HOST=0.0.0.0
      - KITE_PORT=8080
      - KITE_DB_SSL_MODE=require
      - KITE_LOG_LEVEL=info
      - KITE_LOG_FORMAT=json
      - KITE_ENABLE_CORS=true
      - KITE_FEATURE_NAMESPACE_CHECKING=true
      - KITE_FEATURE_WEBHOOKS=true
      - KITE_FEATURE_METRICS=true
      - KITE_READ_TIMEOUT=30s
      - KITE_WRITE_TIMEOUT=30s
      - KITE_IDLE_TIMEOUT=60s
      - KITE_SHUTDOWN_TIMEOUT=10s

# Not using external secrets here for development env.
secretGenerator:
  - name: kite-database-credentials
    namespace: konflux-kite
    type: Opaque
    literals:
      - DB_USER=kite
      - DB_PASSWORD=postgres
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_NAME=issuesdb
